/*
 *      CodeAPI - Framework to generate Java code and Bytecode code. <https://github.com/JonathanxD/CodeAPI>
 *
 *         The MIT License (MIT)
 *
 *      Copyright (c) 2017 TheRealBuggy/JonathanxD (https://github.com/JonathanxD/ & https://github.com/TheRealBuggy/) <jonathan.scripter@programmer.net>
 *      Copyright (c) contributors
 *
 *
 *      Permission is hereby granted, free of charge, to any person obtaining a copy
 *      of this software and associated documentation files (the "Software"), to deal
 *      in the Software without restriction, including without limitation the rights
 *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *      copies of the Software, and to permit persons to whom the Software is
 *      furnished to do so, subject to the following conditions:
 *
 *      The above copyright notice and this permission notice shall be included in
 *      all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *      THE SOFTWARE.
 */
package com.github.jonathanxd.codeapi.builder

import com.github.jonathanxd.codeapi.base.AnonymousClass
import com.github.jonathanxd.codeapi.base.impl.AnonymousClassImpl

// Generated by BuilderGen
open class AnonymousClassBuilder() : AnonymousClass.Builder<AnonymousClass, AnonymousClassBuilder> {

    /**
     * See [AnonymousClass.qualifiedName]
     */
    lateinit var qualifiedName: kotlin.String

    /**
     * See [AnonymousClass.constructorSpec]
     */
    lateinit var constructorSpec: com.github.jonathanxd.codeapi.common.TypeSpec

    /**
     * See [AnonymousClass.arguments]
     */
    var arguments: kotlin.collections.List<com.github.jonathanxd.codeapi.CodePart> = emptyList()

    /**
     * See [AnonymousClass.constructorBody]
     */
    var constructorBody: com.github.jonathanxd.codeapi.CodeSource = com.github.jonathanxd.codeapi.CodeSource.empty()

    /**
     * See [AnonymousClass.annotations]
     */
    var annotations: kotlin.collections.List<com.github.jonathanxd.codeapi.base.Annotation> = emptyList()

    /**
     * See [AnonymousClass.body]
     */
    var body: com.github.jonathanxd.codeapi.CodeSource = com.github.jonathanxd.codeapi.CodeSource.empty()

    /**
     * See [AnonymousClass.comments]
     */
    var comments: com.github.jonathanxd.codeapi.base.comment.Comments = com.github.jonathanxd.codeapi.base.comment.Comments.Absent

    /**
     * See [AnonymousClass.superClass]
     */
    lateinit var superClass: com.github.jonathanxd.codeapi.type.CodeType

    /**
     * See [AnonymousClass.outerClass]
     */
    var outerClass: com.github.jonathanxd.codeapi.type.CodeType? = null

    constructor(defaults: AnonymousClass) : this() {
        this.qualifiedName = defaults.specifiedName
        this.constructorSpec = defaults.constructorSpec
        this.arguments = defaults.arguments
        this.constructorBody = defaults.constructorBody
        this.annotations = defaults.annotations
        this.body = defaults.body
        this.comments = defaults.comments
        this.superClass = defaults.superClass
        this.outerClass = defaults.outerClass
    }


    /**
     * See [AnonymousClass.qualifiedName]
     */
    override fun withQualifiedName(value: kotlin.String): AnonymousClassBuilder {
        this.qualifiedName = value
        return this
    }


    /**
     * See [AnonymousClass.constructorSpec]
     */
    override fun withConstructorSpec(value: com.github.jonathanxd.codeapi.common.TypeSpec): AnonymousClassBuilder {
        this.constructorSpec = value
        return this
    }


    /**
     * See [AnonymousClass.arguments]
     */
    override fun withArguments(value: kotlin.collections.List<com.github.jonathanxd.codeapi.CodePart>): AnonymousClassBuilder {
        this.arguments = value
        return this
    }


    /**
     * See [AnonymousClass.arguments]
     */
    override fun withArguments(vararg values: com.github.jonathanxd.codeapi.CodePart): AnonymousClassBuilder {
        this.arguments = values.toList()
        return this
    }


    /**
     * See [AnonymousClass.constructorBody]
     */
    override fun withConstructorBody(value: com.github.jonathanxd.codeapi.CodeSource): AnonymousClassBuilder {
        this.constructorBody = value
        return this
    }


    /**
     * See [AnonymousClass.annotations]
     */
    override fun withAnnotations(value: kotlin.collections.List<com.github.jonathanxd.codeapi.base.Annotation>): AnonymousClassBuilder {
        this.annotations = value
        return this
    }


    /**
     * See [AnonymousClass.annotations]
     */
    override fun withAnnotations(vararg values: com.github.jonathanxd.codeapi.base.Annotation): AnonymousClassBuilder {
        this.annotations = values.toList()
        return this
    }


    /**
     * See [AnonymousClass.body]
     */
    override fun withBody(value: com.github.jonathanxd.codeapi.CodeSource): AnonymousClassBuilder {
        this.body = value
        return this
    }


    /**
     * See [AnonymousClass.comments]
     */
    override fun withComments(value: com.github.jonathanxd.codeapi.base.comment.Comments): AnonymousClassBuilder {
        this.comments = value
        return this
    }


    /**
     * See [AnonymousClass.superClass]
     */
    override fun withSuperClass(value: com.github.jonathanxd.codeapi.type.CodeType?): AnonymousClassBuilder {
        this.superClass = value!!
        return this
    }


    /**
     * See [AnonymousClass.outerClass]
     */
    override fun withOuterClass(value: com.github.jonathanxd.codeapi.type.CodeType?): AnonymousClassBuilder {
        this.outerClass = value
        return this
    }

    override fun build(): AnonymousClass = AnonymousClassImpl(
            qualifiedName = this.qualifiedName,
            constructorSpec = this.constructorSpec,
            arguments = this.arguments,
            constructorBody = this.constructorBody,
            annotations = this.annotations,
            body = this.body,
            comments = this.comments,
            superClass = this.superClass,
            outerClass = this.outerClass
    )


    companion object {
        @JvmStatic
        fun builder() = AnonymousClassBuilder()
    }
}