/*
 *      CodeAPI - Framework to generate Java code and Bytecode code. <https://github.com/JonathanxD/CodeAPI>
 *
 *         The MIT License (MIT)
 *
 *      Copyright (c) 2017 TheRealBuggy/JonathanxD (https://github.com/JonathanxD/ & https://github.com/TheRealBuggy/) <jonathan.scripter@programmer.net>
 *      Copyright (c) contributors
 *
 *
 *      Permission is hereby granted, free of charge, to any person obtaining a copy
 *      of this software and associated documentation files (the "Software"), to deal
 *      in the Software without restriction, including without limitation the rights
 *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *      copies of the Software, and to permit persons to whom the Software is
 *      furnished to do so, subject to the following conditions:
 *
 *      The above copyright notice and this permission notice shall be included in
 *      all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *      THE SOFTWARE.
 */
package com.github.jonathanxd.codeapi.builder

import com.github.jonathanxd.codeapi.base.impl.CastImpl
import com.github.jonathanxd.codeapi.base.Cast

// Generated by BuilderGen
class CastBuilder(): Builder<Cast, CastBuilder>() {
    var originalType: com.github.jonathanxd.codeapi.type.CodeType? = null
    lateinit var targetType: com.github.jonathanxd.codeapi.type.CodeType
    lateinit var castedPart: com.github.jonathanxd.codeapi.CodePart

    constructor(defaults: Cast) : this() {
        this.originalType = defaults.originalType
        this.targetType = defaults.targetType
        this.castedPart = defaults.castedPart
    }

    fun withOriginalType(value: com.github.jonathanxd.codeapi.type.CodeType?): CastBuilder {
        this.originalType = value
        return this
    }

    fun withTargetType(value: com.github.jonathanxd.codeapi.type.CodeType): CastBuilder {
        this.targetType = value
        return this
    }

    fun withCastedPart(value: com.github.jonathanxd.codeapi.CodePart): CastBuilder {
        this.castedPart = value
        return this
    }

    override fun build(): Cast = CastImpl(
            originalType = this.originalType,
            targetType = this.targetType,
            castedPart = this.castedPart
    )
}