/*
 *      CodeAPI - Framework to generate Java code and Bytecode code. <https://github.com/JonathanxD/CodeAPI>
 *
 *         The MIT License (MIT)
 *
 *      Copyright (c) 2017 TheRealBuggy/JonathanxD (https://github.com/JonathanxD/ & https://github.com/TheRealBuggy/) <jonathan.scripter@programmer.net>
 *      Copyright (c) contributors
 *
 *
 *      Permission is hereby granted, free of charge, to any person obtaining a copy
 *      of this software and associated documentation files (the "Software"), to deal
 *      in the Software without restriction, including without limitation the rights
 *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *      copies of the Software, and to permit persons to whom the Software is
 *      furnished to do so, subject to the following conditions:
 *
 *      The above copyright notice and this permission notice shall be included in
 *      all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *      THE SOFTWARE.
 */
package com.github.jonathanxd.codeapi.builder

import com.github.jonathanxd.codeapi.base.impl.comment.CommentsImpl
import com.github.jonathanxd.codeapi.base.comment.Comments

// Generated by BuilderGen
open class CommentsBuilder(): Comments.Builder<Comments, CommentsBuilder> {

    /**
     * See [Comments.comments]
     */
    var comments: kotlin.collections.List<com.github.jonathanxd.codeapi.base.comment.Comment> = emptyList()

    /**
     * See [Comments.type]
     */
    lateinit var type: com.github.jonathanxd.codeapi.base.comment.Comments.Type

    constructor(defaults: Comments) : this() {
        this.comments = defaults.comments
        this.type = defaults.type
    }


    /**
     * See [Comments.comments]
     */
    override fun withComments(value: kotlin.collections.List<com.github.jonathanxd.codeapi.base.comment.Comment>): CommentsBuilder {
        this.comments = value
        return this
    }


    /**
     * See [Comments.comments]
     */
    override fun withComments(vararg values: com.github.jonathanxd.codeapi.base.comment.Comment): CommentsBuilder {
        this.comments = values.toList()
        return this
    }


    /**
     * See [Comments.type]
     */
    override fun withType(value: com.github.jonathanxd.codeapi.base.comment.Comments.Type): CommentsBuilder {
        this.type = value
        return this
    }

    override fun build(): Comments = CommentsImpl(
            comments = this.comments,
            type = this.type
    )


    companion object {
        @JvmStatic
        fun builder() = CommentsBuilder()
    }
}