/*
 *      CodeAPI - Framework to generate Java code and Bytecode code. <https://github.com/JonathanxD/CodeAPI>
 *
 *         The MIT License (MIT)
 *
 *      Copyright (c) 2017 TheRealBuggy/JonathanxD (https://github.com/JonathanxD/ & https://github.com/TheRealBuggy/) <jonathan.scripter@programmer.net>
 *      Copyright (c) contributors
 *
 *
 *      Permission is hereby granted, free of charge, to any person obtaining a copy
 *      of this software and associated documentation files (the "Software"), to deal
 *      in the Software without restriction, including without limitation the rights
 *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *      copies of the Software, and to permit persons to whom the Software is
 *      furnished to do so, subject to the following conditions:
 *
 *      The above copyright notice and this permission notice shall be included in
 *      all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *      THE SOFTWARE.
 */
package com.github.jonathanxd.codeapi.builder

import com.github.jonathanxd.codeapi.base.impl.FieldDeclarationImpl
import com.github.jonathanxd.codeapi.base.FieldDeclaration

// Generated by BuilderGen
open class FieldDeclarationBuilder(): FieldDeclaration.Builder<FieldDeclaration, FieldDeclarationBuilder> {

    /**
     * See [FieldDeclaration.annotations]
     */
    var annotations: kotlin.collections.List<com.github.jonathanxd.codeapi.base.Annotation> = emptyList()

    /**
     * See [FieldDeclaration.value]
     */
    var value: com.github.jonathanxd.codeapi.CodePart? = null

    /**
     * See [FieldDeclaration.modifiers]
     */
    var modifiers: kotlin.collections.Set<com.github.jonathanxd.codeapi.common.CodeModifier> = emptySet()

    /**
     * See [FieldDeclaration.name]
     */
    lateinit var name: kotlin.String

    /**
     * See [FieldDeclaration.type]
     */
    lateinit var type: com.github.jonathanxd.codeapi.type.CodeType

    constructor(defaults: FieldDeclaration) : this() {
        this.annotations = defaults.annotations
        this.value = defaults.value
        this.modifiers = defaults.modifiers
        this.name = defaults.name
        this.type = defaults.type
    }


    /**
     * See [FieldDeclaration.annotations]
     */
    override fun withAnnotations(value: kotlin.collections.List<com.github.jonathanxd.codeapi.base.Annotation>): FieldDeclarationBuilder {
        this.annotations = value
        return this
    }


    /**
     * See [FieldDeclaration.annotations]
     */
    override fun withAnnotations(vararg values: com.github.jonathanxd.codeapi.base.Annotation): FieldDeclarationBuilder {
        this.annotations = values.toList()
        return this
    }


    /**
     * See [FieldDeclaration.value]
     */
    override fun withValue(value: com.github.jonathanxd.codeapi.CodePart?): FieldDeclarationBuilder {
        this.value = value
        return this
    }


    /**
     * See [FieldDeclaration.modifiers]
     */
    override fun withModifiers(value: kotlin.collections.Set<com.github.jonathanxd.codeapi.common.CodeModifier>): FieldDeclarationBuilder {
        this.modifiers = value
        return this
    }


    /**
     * See [FieldDeclaration.modifiers]
     */
    override fun withModifiers(vararg values: com.github.jonathanxd.codeapi.common.CodeModifier): FieldDeclarationBuilder {
        this.modifiers = values.toSet()
        return this
    }


    /**
     * See [FieldDeclaration.name]
     */
    override fun withName(value: kotlin.String): FieldDeclarationBuilder {
        this.name = value
        return this
    }


    /**
     * See [FieldDeclaration.type]
     */
    override fun withType(value: com.github.jonathanxd.codeapi.type.CodeType?): FieldDeclarationBuilder {
        this.type = value!!
        return this
    }

    override fun build(): FieldDeclaration = FieldDeclarationImpl(
            annotations = this.annotations,
            value = this.value,
            modifiers = this.modifiers,
            name = this.name,
            type = this.type
    )


    companion object {
        @JvmStatic
        fun builder() = FieldDeclarationBuilder()
    }
}