/*
 *      CodeAPI - Framework to generate Java code and Bytecode code. <https://github.com/JonathanxD/CodeAPI>
 *
 *         The MIT License (MIT)
 *
 *      Copyright (c) 2017 TheRealBuggy/JonathanxD (https://github.com/JonathanxD/ & https://github.com/TheRealBuggy/) <jonathan.scripter@programmer.net>
 *      Copyright (c) contributors
 *
 *
 *      Permission is hereby granted, free of charge, to any person obtaining a copy
 *      of this software and associated documentation files (the "Software"), to deal
 *      in the Software without restriction, including without limitation the rights
 *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *      copies of the Software, and to permit persons to whom the Software is
 *      furnished to do so, subject to the following conditions:
 *
 *      The above copyright notice and this permission notice shall be included in
 *      all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *      THE SOFTWARE.
 */
package com.github.jonathanxd.codeapi.builder

import com.github.jonathanxd.codeapi.base.impl.FieldDefinitionImpl
import com.github.jonathanxd.codeapi.base.FieldDefinition

// Generated by BuilderGen
open class FieldDefinitionBuilder(): Builder<FieldDefinition, FieldDefinitionBuilder>() {

    /**
     * See [FieldDefinition.localization]
     */
    var localization: com.github.jonathanxd.codeapi.type.CodeType? = null

    /**
     * See [FieldDefinition.type]
     */
    lateinit var type: com.github.jonathanxd.codeapi.type.CodeType

    /**
     * See [FieldDefinition.value]
     */
    lateinit var value: com.github.jonathanxd.codeapi.CodePart

    /**
     * See [FieldDefinition.name]
     */
    lateinit var name: kotlin.String

    /**
     * See [FieldDefinition.target]
     */
    var target: com.github.jonathanxd.codeapi.CodePart? = null

    constructor(defaults: FieldDefinition) : this() {
        this.localization = defaults.localization
        this.type = defaults.type
        this.value = defaults.value
        this.name = defaults.name
        this.target = defaults.target
    }


    /**
     * See [FieldDefinition.localization]
     */
    fun withLocalization(value: com.github.jonathanxd.codeapi.type.CodeType?): FieldDefinitionBuilder {
        this.localization = value
        return this
    }


    /**
     * See [FieldDefinition.type]
     */
    fun withType(value: com.github.jonathanxd.codeapi.type.CodeType): FieldDefinitionBuilder {
        this.type = value
        return this
    }


    /**
     * See [FieldDefinition.value]
     */
    fun withValue(value: com.github.jonathanxd.codeapi.CodePart): FieldDefinitionBuilder {
        this.value = value
        return this
    }


    /**
     * See [FieldDefinition.name]
     */
    fun withName(value: kotlin.String): FieldDefinitionBuilder {
        this.name = value
        return this
    }


    /**
     * See [FieldDefinition.target]
     */
    fun withTarget(value: com.github.jonathanxd.codeapi.CodePart?): FieldDefinitionBuilder {
        this.target = value
        return this
    }

    override fun build(): FieldDefinition = FieldDefinitionImpl(
            localization = this.localization,
            type = this.type,
            value = this.value,
            name = this.name,
            target = this.target
    )


    companion object {
        @JvmStatic
        fun builder() = FieldDefinitionBuilder()
    }
}