/*
 *      CodeAPI - Framework to generate Java code and Bytecode code. <https://github.com/JonathanxD/CodeAPI>
 *
 *         The MIT License (MIT)
 *
 *      Copyright (c) 2017 TheRealBuggy/JonathanxD (https://github.com/JonathanxD/ & https://github.com/TheRealBuggy/) <jonathan.scripter@programmer.net>
 *      Copyright (c) contributors
 *
 *
 *      Permission is hereby granted, free of charge, to any person obtaining a copy
 *      of this software and associated documentation files (the "Software"), to deal
 *      in the Software without restriction, including without limitation the rights
 *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *      copies of the Software, and to permit persons to whom the Software is
 *      furnished to do so, subject to the following conditions:
 *
 *      The above copyright notice and this permission notice shall be included in
 *      all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *      THE SOFTWARE.
 */
package com.github.jonathanxd.codeapi.builder

import com.github.jonathanxd.codeapi.base.impl.MethodFragmentImpl
import com.github.jonathanxd.codeapi.base.MethodFragment

// Generated by BuilderGen
open class MethodFragmentBuilder(): Builder<MethodFragment, MethodFragmentBuilder>() {

    /**
     * See [MethodFragment.declaringType]
     */
    lateinit var declaringType: com.github.jonathanxd.codeapi.base.TypeDeclaration

    /**
     * See [MethodFragment.scope]
     */
    lateinit var scope: com.github.jonathanxd.codeapi.common.Scope

    /**
     * See [MethodFragment.arguments]
     */
    var arguments: kotlin.collections.List<com.github.jonathanxd.codeapi.common.CodeArgument> = emptyList()

    /**
     * See [MethodFragment.description]
     */
    lateinit var description: com.github.jonathanxd.codeapi.common.TypeSpec

    /**
     * See [MethodFragment.parameters]
     */
    var parameters: kotlin.collections.List<com.github.jonathanxd.codeapi.common.CodeParameter> = emptyList()

    /**
     * See [MethodFragment.body]
     */
    var body: com.github.jonathanxd.codeapi.CodeSource = com.github.jonathanxd.codeapi.CodeSource.empty()

    constructor(defaults: MethodFragment) : this() {
        this.declaringType = defaults.declaringType
        this.scope = defaults.scope
        this.arguments = defaults.arguments
        this.description = defaults.description
        this.parameters = defaults.parameters
        this.body = defaults.body
    }


    /**
     * See [MethodFragment.declaringType]
     */
    fun withDeclaringType(value: com.github.jonathanxd.codeapi.base.TypeDeclaration): MethodFragmentBuilder {
        this.declaringType = value
        return this
    }


    /**
     * See [MethodFragment.scope]
     */
    fun withScope(value: com.github.jonathanxd.codeapi.common.Scope): MethodFragmentBuilder {
        this.scope = value
        return this
    }


    /**
     * See [MethodFragment.arguments]
     */
    fun withArguments(value: kotlin.collections.List<com.github.jonathanxd.codeapi.common.CodeArgument>): MethodFragmentBuilder {
        this.arguments = value
        return this
    }


    /**
     * See [MethodFragment.arguments]
     */
    fun withArguments(vararg values: com.github.jonathanxd.codeapi.common.CodeArgument): MethodFragmentBuilder {
        this.arguments = values.toList()
        return this
    }


    /**
     * See [MethodFragment.description]
     */
    fun withDescription(value: com.github.jonathanxd.codeapi.common.TypeSpec): MethodFragmentBuilder {
        this.description = value
        return this
    }


    /**
     * See [MethodFragment.parameters]
     */
    fun withParameters(value: kotlin.collections.List<com.github.jonathanxd.codeapi.common.CodeParameter>): MethodFragmentBuilder {
        this.parameters = value
        return this
    }


    /**
     * See [MethodFragment.parameters]
     */
    fun withParameters(vararg values: com.github.jonathanxd.codeapi.common.CodeParameter): MethodFragmentBuilder {
        this.parameters = values.toList()
        return this
    }


    /**
     * See [MethodFragment.body]
     */
    fun withBody(value: com.github.jonathanxd.codeapi.CodeSource): MethodFragmentBuilder {
        this.body = value
        return this
    }

    override fun build(): MethodFragment = MethodFragmentImpl(
            declaringType = this.declaringType,
            scope = this.scope,
            arguments = this.arguments,
            description = this.description,
            parameters = this.parameters,
            body = this.body
    )


    companion object {
        @JvmStatic
        fun builder() = MethodFragmentBuilder()
    }
}