/*
 *      CodeAPI - Framework to generate Java code and Bytecode code. <https://github.com/JonathanxD/CodeAPI>
 *
 *         The MIT License (MIT)
 *
 *      Copyright (c) 2017 TheRealBuggy/JonathanxD (https://github.com/JonathanxD/ & https://github.com/TheRealBuggy/) <jonathan.scripter@programmer.net>
 *      Copyright (c) contributors
 *
 *
 *      Permission is hereby granted, free of charge, to any person obtaining a copy
 *      of this software and associated documentation files (the "Software"), to deal
 *      in the Software without restriction, including without limitation the rights
 *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *      copies of the Software, and to permit persons to whom the Software is
 *      furnished to do so, subject to the following conditions:
 *
 *      The above copyright notice and this permission notice shall be included in
 *      all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *      THE SOFTWARE.
 */
package com.github.jonathanxd.codeapi.builder

import com.github.jonathanxd.codeapi.base.impl.TryWithResourcesImpl
import com.github.jonathanxd.codeapi.base.TryWithResources

// Generated by BuilderGen
open class TryWithResourcesBuilder(): Builder<TryWithResources, TryWithResourcesBuilder>() {

    /**
     * See [TryWithResources.variable]
     */
    lateinit var variable: com.github.jonathanxd.codeapi.base.VariableDeclaration

    /**
     * See [TryWithResources.catchStatements]
     */
    var catchStatements: kotlin.collections.List<com.github.jonathanxd.codeapi.base.CatchStatement> = emptyList()

    /**
     * See [TryWithResources.finallyStatement]
     */
    var finallyStatement: com.github.jonathanxd.codeapi.CodeSource? = null

    /**
     * See [TryWithResources.body]
     */
    var body: com.github.jonathanxd.codeapi.CodeSource? = null

    constructor(defaults: TryWithResources) : this() {
        this.variable = defaults.variable
        this.catchStatements = defaults.catchStatements
        this.finallyStatement = defaults.finallyStatement
        this.body = defaults.body
    }


    /**
     * See [TryWithResources.variable]
     */
    fun withVariable(value: com.github.jonathanxd.codeapi.base.VariableDeclaration): TryWithResourcesBuilder {
        this.variable = value
        return this
    }


    /**
     * See [TryWithResources.catchStatements]
     */
    fun withCatchStatements(value: kotlin.collections.List<com.github.jonathanxd.codeapi.base.CatchStatement>): TryWithResourcesBuilder {
        this.catchStatements = value
        return this
    }


    /**
     * See [TryWithResources.catchStatements]
     */
    fun withCatchStatements(vararg values: com.github.jonathanxd.codeapi.base.CatchStatement): TryWithResourcesBuilder {
        this.catchStatements = values.toList()
        return this
    }


    /**
     * See [TryWithResources.finallyStatement]
     */
    fun withFinallyStatement(value: com.github.jonathanxd.codeapi.CodeSource?): TryWithResourcesBuilder {
        this.finallyStatement = value
        return this
    }


    /**
     * See [TryWithResources.body]
     */
    fun withBody(value: com.github.jonathanxd.codeapi.CodeSource?): TryWithResourcesBuilder {
        this.body = value
        return this
    }

    override fun build(): TryWithResources = TryWithResourcesImpl(
            variable = this.variable,
            catchStatements = this.catchStatements,
            finallyStatement = this.finallyStatement,
            body = this.body
    )


    companion object {
        @JvmStatic
        fun builder() = TryWithResourcesBuilder()
    }
}