/*
 *      CodeAPI - Framework to generate Java code and Bytecode code. <https://github.com/JonathanxD/CodeAPI>
 *
 *         The MIT License (MIT)
 *
 *      Copyright (c) 2017 TheRealBuggy/JonathanxD (https://github.com/JonathanxD/ & https://github.com/TheRealBuggy/) <jonathan.scripter@programmer.net>
 *      Copyright (c) contributors
 *
 *
 *      Permission is hereby granted, free of charge, to any person obtaining a copy
 *      of this software and associated documentation files (the "Software"), to deal
 *      in the Software without restriction, including without limitation the rights
 *      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *      copies of the Software, and to permit persons to whom the Software is
 *      furnished to do so, subject to the following conditions:
 *
 *      The above copyright notice and this permission notice shall be included in
 *      all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *      THE SOFTWARE.
 */
package com.github.jonathanxd.codeapi.builder

import com.github.jonathanxd.codeapi.base.impl.VariableOperateImpl
import com.github.jonathanxd.codeapi.base.VariableOperate

// Generated by BuilderGen
class VariableOperateBuilder(): Builder<VariableOperate, VariableOperateBuilder>() {

    /**
     * See [VariableOperate.target]
     */
    lateinit var target: com.github.jonathanxd.codeapi.CodePart

    /**
     * See [VariableOperate.name]
     */
    lateinit var name: kotlin.String

    /**
     * See [VariableOperate.localization]
     */
    var localization: com.github.jonathanxd.codeapi.type.CodeType? = null

    /**
     * See [VariableOperate.variableType]
     */
    lateinit var variableType: com.github.jonathanxd.codeapi.type.CodeType

    /**
     * See [VariableOperate.value]
     */
    var value: com.github.jonathanxd.codeapi.CodePart? = null

    /**
     * See [VariableOperate.operation]
     */
    lateinit var operation: com.github.jonathanxd.codeapi.operator.Operator

    constructor(defaults: VariableOperate) : this() {
        this.target = defaults.target
        this.name = defaults.name
        this.localization = defaults.localization
        this.variableType = defaults.variableType
        this.value = defaults.value
        this.operation = defaults.operation
    }


    /**
     * See [VariableOperate.target]
     */
    fun withTarget(value: com.github.jonathanxd.codeapi.CodePart): VariableOperateBuilder {
        this.target = value
        return this
    }


    /**
     * See [VariableOperate.name]
     */
    fun withName(value: kotlin.String): VariableOperateBuilder {
        this.name = value
        return this
    }


    /**
     * See [VariableOperate.localization]
     */
    fun withLocalization(value: com.github.jonathanxd.codeapi.type.CodeType?): VariableOperateBuilder {
        this.localization = value
        return this
    }


    /**
     * See [VariableOperate.variableType]
     */
    fun withVariableType(value: com.github.jonathanxd.codeapi.type.CodeType): VariableOperateBuilder {
        this.variableType = value
        return this
    }


    /**
     * See [VariableOperate.value]
     */
    fun withValue(value: com.github.jonathanxd.codeapi.CodePart?): VariableOperateBuilder {
        this.value = value
        return this
    }


    /**
     * See [VariableOperate.operation]
     */
    fun withOperation(value: com.github.jonathanxd.codeapi.operator.Operator): VariableOperateBuilder {
        this.operation = value
        return this
    }

    override fun build(): VariableOperate = VariableOperateImpl(
            target = this.target,
            name = this.name,
            localization = this.localization,
            variableType = this.variableType,
            value = this.value,
            operation = this.operation
    )


    companion object {
        @JvmStatic
        fun builder() = VariableOperateBuilder()
    }
}